version: "3"

volumes:
  mariadb:
    driver: local
  mysql:
    driver: local
  backup:
    driver: local

networks:
  db:
    driver: bridge

services:

  init:
    image: mloitzl/mysql:4.1.22
    networks:
      db:
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      MYSQL_INIT_USER: MYSQL_INIT_USER
      MYSQL_INIT_PASSWORD: MYSQL_INIT_PASSWORD
      MYSQL_HOST: mysql
      HEM_DB_NAME: hem
    entrypoint: ["/bin/sh", "/init-db.sh"]
    volumes:
      - ./init/init-db.sh:/init-db.sh
      - ./init/hem_backup.sql:/hem_backup.sql
      - ./init/create_tables_mysql_4_1_2+.sql:/create_tables_mysql_4_1_2+.sql

  hem:
    image: mloitzl/hem:0.4.1
    build:
      context: .
      dockerfile: Dockerfile.hem
    restart: always
    ports:
      - "9080:80"
    entrypoint: /bin/sh -c "apachectl start; while true; do sleep 1s; echo '.'; done"
    environment:
      PMA_USER: pmauser
      MYSQL_HOST: mysql
      MYSQL_DB: hem
    networks:
      db:

  mysql:
    image: mloitzl/mysql:4.1.22
    restart: always
    environment:
      MYSQL_INIT_USER: MYSQL_INIT_USER
      MYSQL_INIT_PASSWORD: MYSQL_INIT_PASSWORD
      MYSQL_INIT_HOST: "%init%"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "--silent"]
      interval: 5s
      retries: 10
    volumes:
      - mysql:/usr/local/mysql/var
      - backup:/backup/mysql
    networks:
      db:

  phpmyadmin:
    image: mloitzl/phpmyadmin:2.11.11.3
    build:
      context: .
      dockerfile: Dockerfile.phpmyadmin
    restart: always
    ports:
      - "9081:80"
    entrypoint: /bin/sh -c "apachectl start; while true; do sleep 1s; echo '.'; done"
    environment:
      PMA_USER: pmauser
      PMA_HOST: mysql
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      db:

