<?php
define('ADD_ENVIRONMENT_DATA', 13);
define('CHANGE_ACTIVE_FLAG', 6);
define('CHANGE_GROUP_MEMBERSHIP', 2);
define('CHANGE_OTHER_ENVIRONMENTS', 20);
define('CHANGE_OTHER_FINDINGS', 14);
define('CHANGE_OTHER_PASSWORD', 4);
define('CHANGE_OTHER_RATINGS', 15);
define('CHANGE_OTHER_USERNAME', 5);
define('CHANGE_OTHER_USERS', 3);
define('COLLECT_FINDINGS', 10);
define('COLLECT_RATINGS', 16);
define('EDIT_HEURISTIC_SETS', 7);
define('MANAGER_ENVIRONMENTS', 12);
define('MANAGE_ENVIRONMENTS', 19);
define('MANAGE_HEURISTICS', 11);
define('MANAGE_PROJECTS', 9);
define('MANAGE_RATINGSCALES', 17);
define('MANAGE_RATINGSCHEMES', 18);
define('MANAGE_REPORTS', 21);
define('MERGE_FINDINGS', 8);
define('VIEW_MANAGER_DATA', 1);
?>